packages:
  darwin:
    taps:
      - 'homebrew/cask-versions'
      - 'homebrew/cask-fonts'
    brews:
      - 'fd'
      - 'fzf'
      - 'zoxide'
      - 'gh'
      - 'git'
      - 'jq'
      - 'thefuck'
      - 'tmux'
      - 'starship'
      - 'zsh-autosuggestions'
      - 'zsh-completions'
    casks:
      - 'amethyst'
      - 'font-ricty-diminished'
      - 'google-cloud-sdk'
      - 'wezterm-nightly'

