packages:
  darwin:
    casks:
      - "wezterm@nightly"
      - "font-hackgen"
      - "nikitabobko/tap/aerospace"
  cmdline:
    - "aqua"
    - "bat"
    - "colima"
    - "docker"
    - "fd"
    - "fzf"
    - "git"
    - "jq"
    - "oxker"
    - "ripgrep"
    - "thefuck"
    - "tmux"
    - "typos-cli"
    - "zsh-autosuggestions"
    - "zsh-completions"
    - "zoxide"
    - "mise"
    - "lazygit"
