packages:
  darwin:
    taps:
      - "FelixKratz/formulae" # https://github.com/FelixKratz/JankyBorders
    casks:
      - "wezterm@nightly"
      - "nikitabobko/tap/aerospace"
      - "obsidian"
      - "chatgpt"
    defaults:
      - "colima"
      - "docker"
      - "borders" # https://github.com/FelixKratz/JankyBorders
