packages:
  darwin:
    taps:
    brews:
      - 'bat'
      - 'fd'
      - 'fzf'
      - 'zoxide'
      - 'gh'
      - 'git'
      - 'jq'
      - 'ripgrep'
      - 'thefuck'
      - 'tmux'
      - 'starship'
      - 'zsh-autosuggestions'
      - 'zsh-completions'
    casks:
      - 'google-cloud-sdk'
      - 'wezterm@nightly'
      - 'font-hackgen'
      - 'nikitabobko/tap/aerospace'

