packages:
  darwin:
    taps:
      - 'homebrew/cask-versions'
      - 'homebrew/cask-fonts'
    brews:
      - 'gh'
      - 'git'
      - 'jq'
      - 'tmux'
      - 'starship'
      - 'zsh-autosuggestions'
      - 'zsh-completions'
    casks:
      - 'wezterm-nightly'
      - 'font-cousine-nerd-font'
      - 'font-fira-code-nerd-font'

