packages:
  darwin:
    casks:
      - "wezterm@nightly"
      - "font-hackgen"
  cmdline:
    - "aqua"
    - "bat"
    - "colima"
    - "docker"
    - "fd"
    - "git"
    - "gitmux"
    - "jq"
    - "ripgrep"
    - "tmux"
    - "typos-cli"
    - "zsh-autosuggestions"
    - "zsh-completions"
    - "zoxide"
    - "mise"
    - "eza"
    - "git-delta"
