packages:
  darwin:
    taps:
    casks:
      - 'wezterm@nightly'
      - 'font-hackgen'
      - 'nikitabobko/tap/aerospace'
  cmdline:
      - 'bat'
      - 'fd'
      - 'fzf'
      - 'gh'
      - 'git'
      - 'jq'
      - 'ripgrep'
      - 'thefuck'
      - 'tmux'
      - 'typos-cli'
      - 'starship'
      - 'zsh-autosuggestions'
      - 'zsh-completions'
      - 'zoxide'

