live_config_reload = true

[font]
size = 17.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[shell]
args = ["-l", "-c", "tmux a -t 0 || tmux"]
program = "/bin/zsh"

[window]
opacity = 0.9

[window.dimensions]
columns = 200
lines = 60

[window.padding]
x = 8
y = 4
