
# ~/.config/starship.toml
[aws]
disabled = true

[gcloud]
disabled = true

[memory_usage]
disabled = true
threshold = -1
symbol = '󰍛 '
style = 'bold dimmed green'

[golang]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[nodejs]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

