[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold blue'

[aws.region_aliases]
ap-northeast-1 = 'ja'


# ~/.config/starship.toml

[memory_usage]
disabled = false
threshold = -1
symbol = '󰍛 '
style = 'bold dimmed green'
